# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170409_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='goodreads_id',
            field=models.IntegerField(default=None),
        ),
    ]
