# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170409_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='goodreads_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
